global:
  scrape_interval:     5s
  evaluation_interval: 5s

  labels:
    cluster: swarm
    replica: "1"

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus-swarm'

scrape_configs:
  - job_name: 'prometheus'
    dns_sd_configs:
    - names:
      - 'tasks.prometheus'
      type: 'A'
      port: 9090

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'docker-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.docker-exporter'
      type: 'A'
      port: 4999
     
  - job_name: 'user'
    dns_sd_configs:
    - names:
      - 'tasks.user'
      type: 'A'
      port: 80

  - job_name: 'front-end'
    dns_sd_configs:
    - names:
      - 'tasks.front-end'
      type: 'A'
      port: 80
  
  - job_name: 'catalogue'
    dns_sd_configs:
    - names:
      - 'tasks.catalogue'
      type: 'A'
      port: 80
  
  - job_name: 'payment'
    dns_sd_configs:
    - names:
      - 'tasks.payment'
      type: 'A'
      port: 80
  
  - job_name: 'carts'
    dns_sd_configs:
    - names:
      - 'tasks.carts'
      type: 'A'
      port: 80
      
  - job_name: 'orders'
    dns_sd_configs:
    - names:
      - 'tasks.orders'
      type: 'A'
      port: 80
  
  - job_name: 'shipping'
    dns_sd_configs:
    - names:
      - 'tasks.shipping'
      type: 'A'
      port: 80

  - job_name: 'queue-master'
    metrics_path: 'prometheus'
    dns_sd_configs:
    - names:
      - 'tasks.queue-master'
      type: 'A'
      port: 80
    
